### ISSUE TITLE
App crashes with IllegalArgumentException Service not registered

### ISSUE THREAD

**Issue by deepakv-z14** [singular-labs/react-native-sdk#79]
We are facing crashes in our app

```
Fatal Exception: java.lang.IllegalArgumentException: Service not registered: com.android.installreferrer.api.InstallReferrerClientImpl$b@71bf14b
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1603)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1745)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
       at com.android.installreferrer.api.InstallReferrerClientImpl.endConnection(InstallReferrerClientImpl.java:2)
       at com.singular.sdk.internal.InstallReferrer.SLGoogleReferrer$1$1.run(SLGoogleReferrer.java:76)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
   ```
   
   "singular-react-native": "3.2.2",
   "react-native": "0.71.12", 
   
   Any way to fix this?

**Comment by shefdanny** [comment]
solved in v3.3.0
